schema: "classroom50/repo-config/v1"
classroom: "f215-digital-design"
assignment: "dd-2026-verilog-labs"
owner:
  username: "f20250705-max"
  id: 318952193
  accepted_at: "2026-08-27T14:14:58Z"
source:
  owner: "f2152026"
  owner_id: 316136693
  repo: "verilog-labs"
  branch: "main"
